dataset:
  name: MNIST
  data_dir: data/mnist
  num_workers: 12
  normalize: true
  download: true
  shuffle: true
  train: true
  pin_memory: true
  batch_size: 128
  num_classes: 40
training_params:
  n_epochs: 101
  display_step: 500
  device_num: [0]
  accelerator: gpu
  weight_init_name: normal
  checkpoint_dir: checkpoints/
  monitor: None
  model:
    input_dim: 64
    architecture: WGAN
    input_size: 28 # set it to 28 for mnist and 32 for cifar10
    pretrained: false
  loss:
    discriminator_loss: WDiscLoss
    generator_loss:  WGenLoss
  optimizer:
    optimizer_name: adam
    lr: 0.0002
    scheduler:
      scheduler_name: None
      step_size: 25
      gamma: 0.5
logger:
  tool: mlflow
  experiment_name: GAN
  run_name: WGAN
  tracking_uri: localhost:5000
  tags: experimental
  log_model: all
