model:
  architecture: "basic-gan"
  input_size: 256
  pretrained: false

trainer:
  n_epochs: 200
  z_dim: 100
  display_step: 500
  batch_size: 128
  lr: 0.0001
  device: "cuda:0"
  loss: "BCEWithLogitsLoss"
  scheduler:
    step_size: 50
    gamma: 0.5


  