Normalize:
  always_apply: True
  mean: [0.5]
  std: [0.5]
  p: 1.0
Resize:
  always_apply: True
  height: 64
  width: 64
  p:  1.0
RandomBrightnessContrast:
  always_apply : True
  p: 0.3
RandomContrast:
  always_apply : True
  p: 0.3
ElasticTransform:
  always_apply : False
  alpha: 10
  sigma: 10
  mask_value: None
  p: 0.0
ImageCompression:
  always_apply : True
  p: 0.3
CenterCrop:
  always_apply: True
  height: 64
  width: 64